version: '3.8'

services:
  python_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - uploads_data:/model_service/uploads
      - outputs_data:/model_service/outputs
      - temp_data:/model_service/temp_backgrounds
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - app_network

  spring_app:
    build:
      context: ../translateeverything
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/translateeverything
    networks:
      - app_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  uploads_data:
  outputs_data:
  temp_data:
  mongodb_data: 